#include <sys/socket.h>

/*
 * @brief Register a connection with random ID in remote relay. Return id >= 0
 * on success and -1 on fail.
 */
int relay_register(int fd, const struct sockaddr *relay_addr);

/*
 * @brief Read response from relay when active listener emerges on connection.
 * Return 0 on success, 1 on fail.
 */
int relay_accept(int fd, struct sockaddr *peer_addr);

/*
 * @brief Connect to already registered connection on relay_addr with id
 * generated by relay_register. Return 0 on success, 1 on fail.
 */
int relay_connect(int fd, int connection_id, const struct sockaddr *relay_addr,
                  struct sockaddr *peer_addr);
